version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    hostname: ${HOSTNAME}
    environment:
      ES_JAVA_OPTS: "-Xmx8g -Xms8g"
      node.name: ${HOSTNAME}
      discovery.zen.ping.unicast.hosts: "elastic-1.gsgr"
      network.publish_host: elastic-2.gsgr 
      network.host: _site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    extra_hosts:
      - "elastic-1.gsgr:172.31.11.4"
      - "elastic-2.gsgr:172.31.1.136"
    #networks:
    #  - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
#    networks:
#      - elk
    depends_on:
      - elasticsearch

#networks:

#  elk:
#    driver: bridge
