# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4

RUN sudo sysctl -w vm.max_map_count=262144
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
